### ISSUE TITLE
Playbook exits to PLAY RECAP without doing anything

### ISSUE THREAD

**Issue by axelsimon** [kultsinuppeli/riotchat#2]
Hi,
I fill all elements as explained in the README.md (letsencrypt email address, etc.), then run:

`ansible-galaxy install -r  requirements.yml`
`ansible-playbook site.yml`
and all I get is
`PLAY RECAP *********************************************************************`

On the server, I can see nothing is in /var/www/html and I don't see anything running in the processes.
Am I missing something?

Thanks in any case for the playbook!

**Comment by kultsinuppeli** [comment]
Hi axelsimon,
I think you're missing an 
"-i inventory" in your ansible playbook command.

Have you tried with

ansible-playbook -i inventory site.yml

**Comment by axelsimon** [comment]
You are correct and I'm an idiot :)
Thanks for your help!
This leads me to another situation:
`fatal: [mymatrixserver.com]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}`
On Debian stable (stretch, 8.7), pip isn't installed by default and is also not a apt package. But apparently, the playbook assumes it's there.

**Comment by kultsinuppeli** [comment]
Hi again,
yeah, I know, I noticed that too on Ubuntu 16.04. I'll fix the roles to handle this correctly. It'll probably take a few days to get to it, but I'll do my best.

**Comment by axelsimon** [comment]
No worries, there is no emergency. There are quite a few roles for installing pip published on ansible-galaxy (`ansible-galaxy search pip` actually returns 58 results). One of them is likely to be good quality and get the job done, but I have little experience with ansible so far so I can't advise as to which one to use.

**Comment by kultsinuppeli** [comment]
So.. this should finally be fixed. I have a bit more options to test now, and runs against a clean server go through.

Yay! Although I took my sweet while.
